### ISSUE TITLE
Source Icons for Game

### ISSUE THREAD

**Issue by RvN-R** [RvN-R/the-planeteers#19]

**Comment by Damianjacob** [comment]
Solid trash can: <i class="fa-solid fa-trash"></i>
Trash can check (for right answers): <i class="fa-solid fa-trash-can-check"></i>
Trash can x (for wrong answers): <i class="fa-solid fa-trash-can-xmark"></i>

**Comment by RvN-R** [comment]
found some useful icons on flaticon that are free to use, bottles, cans, cartons, rubbish, oil and food
https://www.flaticon.com/free-icons/bottle
https://www.flaticon.com/search?word=can&order_by=4
https://www.flaticon.com/search?word=carton&order_by=4
flaticon.com/search?word=rubbish&order_by=4
https://www.flaticon.com/search?word=oil&order_by=4
https://www.flaticon.com/search?word=food&order_by=4
