### ISSUE TITLE
Source Images

### ISSUE THREAD

**Issue by RvN-R** [RvN-R/the-planeteers#8]

**Comment by shahid129** [comment]
https://unsplash.com/photos/OYFHT4X5isg
https://unsplash.com/photos/zLguZrNzcO0
https://unsplash.com/photos/dEOC8M_lmxI
https://unsplash.com/photos/jqgsM3B9Fpo
https://unsplash.com/photos/x8ZStukS2PM
https://unsplash.com/photos/vrbZVyX2k4I
https://unsplash.com/photos/YzSZN3qvHeo
https://www.freepik.com/free-photo/earth-day-graphic-trees-globe-circle-shape-sky-background-remixed-media_15604418.htm#query=earth%20day&position=38&from_view=search

**Comment by Stephanie-Ash** [comment]
**Earth Images:**
https://unsplash.com/photos/yEauzeZU6xo
https://unsplash.com/photos/vhSz50AaFAs
https://pixabay.com/illustrations/factory-chimney-pollution-smoke-6083419/
**If one of us got a 1 month free trial of shutterstock!**
https://www.shutterstock.com/search/sad+earth?kw=free%20pictures&c3apidt=p50848501171&gclid=Cj0KCQjwpImTBhCmARIsAKr58cyrppndVfmYq-QYLUKZXOHV7T7Hh2rmS0wwrbJ5TxFzLcYrmBFMnDAaArTCEALw_wcB&gclsrc=aw.ds

**Pollution and Rubbish images**
https://unsplash.com/photos/RkIsyD_AVvc
https://unsplash.com/photos/WOT8JOjncHk
https://unsplash.com/photos/-4bD2p5zbdA
https://unsplash.com/photos/BJUoZu0mpt0
https://unsplash.com/photos/KNG8l86Qbjo
https://unsplash.com/photos/FoG7PKNYjpM
https://www.pexels.com/photo/drone-shot-of-dumpsite-3174350/
https://unsplash.com/photos/W3y2crFkVIs
https://unsplash.com/photos/5_9inhy4NSE
